#!/bin/bash

VENDOR=lge
DEVICE=mako
DIRSRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" && cd $DIRSRC

BASE=../../../vendor/$VENDOR/$DEVICE/proprietary
rm -rf $BASE/*

for FILE in `cat proprietary-blobs.txt | grep -v ^# | grep -v ^$ | sed -e 's#^/system/##g'`; do
    DIR=`dirname $FILE`
    if [ ! -d $BASE/$DIR ]; then
        mkdir -p $BASE/$DIR
    fi
    adb pull /system/$FILE $BASE/$FILE
done

bash setup-makefiles && cd ../../../

